version: '3.7'

# services:
#   web:
#     build:
#          context: ./app 
#          dockerfile: Dockerfile
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./app/:/opt/app/
#     ports:
#       - 4000:8000
#     env_file:
#       - ./env/django.env
services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 4000:8000
    env_file:
      - ./env/django.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - "postgres_data:/var/postgres/data/"
    env_file: 
       - ./env/posgresql.env

volumes:
  postgres_data: